[world]
name = "OnchainSage"
description = "OnchainSage Dojo World for decentralized signal generation and validation"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/yourusername/onchainsage_dojo"
seed = "onchainsage"

[world.socials]
x = ""
discord = ""
github = ""
telegram = ""

[namespace]
default = "onchainsage"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"onchainsage" = ["onchainsage-signal_system"]

[models]
Signal = { path = "models/signal", schema = { signal_id = "u256", creator = "ContractAddress", asset = "felt252", category = "felt252", confidence = "u8", hash = "felt252", timestamp = "u64", is_validated = "bool" } }
SignalCount = { path = "models/signal", schema = { id = "felt252", count = "u256" } }
SignalValidator = { path = "models/signal", schema = { validator_to_signal_id = "(ContractAddress, u256)", validated = "bool", validation_time = "u64" } }

[systems]
signal = { path = "systems/signal" }
