[package]
name = "onchainsage_dojo"
version = "1.4.0"
cairo-version = "2.9.4"
edition = "2024_07"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" }
starknet = "2.9.4"

[[target.starknet-contract]]
sierra = true
casm = true
sierra-replace-ids = true

[tool.dojo]
initializer_class_hash = "0x0"

[tool.dojo.env]
rpc_url = "http://localhost:5050"
account_address = "0x0"
private_key = "0x0"